# Generated by Django 4.2.5 on 2023-12-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='relationship_type',
            field=models.TextField(choices=[('family', 'Family'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('partner', 'Partner'), ('other', 'Other')], default='other'),
        ),
    ]
